#!/bin/bash

#------------------------------------------------#
# git-current-branch returns the current branch. #
#------------------------------------------------#

branch_name=$(git symbolic-ref -q HEAD)
branch_name=${branch_name##refs/heads/}
branch_name=${branch_name:-HEAD}

echo $branch_name

exit 0